### ISSUE TITLE
Checklist 

### ISSUE THREAD

**Issue by kose-y** [kose-y/DistStat.jl#1]
###  Distributed Array (`distarray.jl`)
Distributed array implementation using MPI. Several basic features are based on  `barche/MPIArrays.jl` with many tweaks, including typing of local arrays. 
- [x] Constructors for MPIArray{T, N, A} [to be documented]: T: element type, N: number of dimensions, A: type of array.
- [x] `Base.similar`: a function that creates another MPIArray of the same type, size, distribution style.
- [x] `copy_into!`
- [x] `redistribute!`
- [x] `forlocalpart!`
- [ ] elementwise access [lower priority]

### Distributed directives (`distdirectives.jl`)
Wrapper over MPI. Each function will use `MPI.COMM_WORLD` as the only possible communicator under the hood (hidden away from the user). For each function, rank 0 is the default root. Size of communication is inferred from the arguments as in PyTorch (requires an additional broadcasting round for `Scatterv`, `Gatherv!`, `Allgatherv!`-- they are not supported in PyTorch!).
- [x] `Barrier()`
- [x] `Bcast!(arr::AbstractArray, root::Integer=0)`
- [x] `Send(arr::AbstractArray, dest::Integer, tag::Integer=0)`
- [x] `Recv!(arr::AbstractArray, src::Integer, tag::Integer=0)`
- [x] `Isend(arr::AbstractArray, dest::Integer, tag::Integer=0)`
- [x] `Irecv!(arr::AbstractArray, src::Integer, tag::Integer=0)`
- [x] `Reduce!(sendarr::AbstractArray, recvarr::AbstractArray, op=MPI.SUM, root::Integer=0)`
- [x] `Allreduce!(arr::AbstractArray, op=MPI.SUM)`
- [x] `Allgatherv!(sendarr::AbstractAray, recvarr::AbstractArray, counts::Vector{Cint})`
- [WON'TDO]`Allgatherv!(sendarr::AbstractArray, recvarr::Vector{AbstractArray})`: counts inferred from `recvarr`
- [x] `Scatterv!(sendarr::AbstractArray, recvarr::AbstractArray, counts::Vector{Cint}, root::Integer=0)`
- [WON'TDO] `Scatterv!(sendarr::Vector{AbstractArray}, recvarr::AbstractArray, root::Integer=0)`: counts inferred from the root's `sendarr` (additional broadcasting round)
- [x] `Gatherv!(sendarr::AbstractArray, recvarr::AbstractArray, counts::Vector{Cint}, root::Integer=0)
- [WON'TDO] `Gatherv!(sendarr::AbstractArray, recvarr::Vector{AbstractArray}, root::Integer=0)`: counts inferred from the root's `recvarr` (additional broadcasting round)

### Reduction (of intrinsic Julia):  `ftn in (:sum, :prod, :min, :max)`
- [x] ftn(::MPIArray{T,N,A}; dims::Colon) where {T,N,A} (returns a singleton of T)
- [x] ftn(::MPIArray{T,N,A}; dims) where {T,N,A}
    - Case 1: The last dimension is included in `dims` (returns A{T,N}(be consistent with Base))
    - Case 2: The last dimension is not included in `dims` (returns MPIArray{T,N,A})
- [x] ftn!(::MPIArray{T,N,A}, arr::MPIArray{T,N,A}) where {T,N,A}
- [x] ftn!(::AbstractArray{T,N}, arr::MPIArray{T,N,A}) where {T,N,A}

_Our PyTorch implementation only supports ranks 0, 1, and 2._

### Blockwise operations/Broadcasting (dot broadcasting in intrinsic Julia, not `MPI.Bcast!`)
- [x] `forlocalpart!`: a `map`-like function for blockwise operations. 
- [x] Full support of dot broadcasting for `MPIArray` [lower priority if our `map`-like blockwise function is satisfactory, VERY HIGH priority otherwise]

_PyTorch version had `apply`, `apply_inplace`, `apply_binary_inplace` as class methods. We need something similar to that... but it would be better to utilize intrinsic dot broadcasting at the same time._ 

### Distributed matrix-matrix/vector multiplication.
Assumption: matrices are split into 1 block row and n block columns. [different from PyTorch implementation, which has row-major layout] Matrices split row-wise is treated as the transpose of matrices split column-wise. Temporary storage supported by keyword arguments; if none provided, it may allocate a new array. We may reuse such temporary space for the same size of multiplication performed repeatedly. The basic syntax is `mul!(C, A, B; temp) -> C`. Scenarios 2, 4, 5 are transposed from those in Page 29 of the draft so that C is column-wise distributed. 
- [x] Scenario 1: (A: r x [p], B: [p] x q, C: r x [q]): inner product, result distributed.
- [x] Scenario 2: (A: r x [p]  , B: p x [q] , C: r x [q]): short and fat matrix multiplied by a fat matrix. More communication than Scenario 1. 
- [x] Scenario 3: (A: r x [p], B: [p] x s, C: r x s): Inner product, result broadcasted. Suited for inner product between two thin matrices.  
- [x] Scenario 4: (A: [p] x r, B: r x [q], C: p x [q]): Outer product, may require a large amount of memory. Often necessary for computing the objective function.
- [x] Scenario 5: (A: r x s, B: r x [q], C: r x [q]): A small, broadcasted matrix multiplied by a distributed matrix. 
- [x] Scenario 6: Matrix-vector multiplications
    - [x] Scenario 6.1: (A: r x [q], B: q x 1, C: r x 1) : a distributed matrix x broadcasted vector, result broadcasted 
    - [x] Scenario 6.2: (A: r x [q], B: [q] x 1, C: r x 1): mat-vec. result broadcasted.
    - [x] Scenario 6.3: (A: [p] x q, B: [q] x 1, C: [p] x 1):  a distributed matrix x broadcasted vector, result distributed 
    - [x] Scenario 6.4: (A: [p] x r, B: r x 1, C: [p] x 1): mat-vec. result distributed. 

### Others
- [x] macro `sync` : a barrier function for ~~both MPI-side and~~ CUDA-side (if enabled)
- [ ] Diagonal matrix (previously used in some of the examples) [lower priority]
- [ ] MPIArray with sparse local arrays (?) [lower priority]
- [x] Basic operators: not necessary if full dot broadcasting is supported, and there is no good replacement among Julia intrinsic operators.... maybe use dot broadcasting in `forlocalpart!` block for now. 
- [x] Basic math functions such as `sqrt`, `abs`, `exp`, `log`: also not necessary if full dot broadcasting is supported... `sqrt`, `exp`, and `log` with `Array` has a different meaning (for square matrices). dot broadcasting in `forlocalpart!` block for now. 
- [x] `cumsum`, `cumprod` [lower priority]: no longer necessary in our examples after the change made in Cox regression (regarding tiebreakers)
- [lower priority]: may be implemented after the experiments.

### Unit Testing
(maybe after experiments) something similar to https://github.com/JuliaParallel/MPI.jl/pull/302

### Examples
- [x] NMF
    - [x] multiplicative
    - [x] alternating projected gradient
- [x] l1-regularized cox
    - [x] power iteration
    - [x] cumsum + sparse matrix-vector mult for computing nll [lower priority until data arrives]
    - [x] main body
- [x] MDS
    - [x] `diag` -- distributed return should return a 1xn "row vector".
    - [x] `fill_diag!`
    - [x] pairwise euclidean_distance
    - [x] main body
- [x] PET
    - [x] check file I/O of `.npz`
    - [x] sparse matrix operations
    - [x] l2-reg MM
    - [x] l1-reg primal-dual
- [ ] MCMC
